//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieRecommendation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public long ID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> YearOfRelease { get; set; }
        public Nullable<int> Director { get; set; }
        public string Language { get; set; }
        public string Producer { get; set; }
        public string PlotSimple { get; set; }
        public string PlotDetailed { get; set; }
        public string AKA { get; set; }
        public string ImdbUrl { get; set; }
        public Nullable<long> PosterId { get; set; }
    
        public virtual Poster Poster { get; set; }
    }
}
